### ISSUE TITLE
[bug] feat-cmdb-ai-handoff: POST /api/cmdb/proposals returns 500 Internal Server Error (db=None breaks audit_service.record_critical_change)

### ISSUE THREAD

**Issue by alexandervazquez98** [alexandervazquez98/next-gen#487]
## Summary

The HITL CI proposal workflow introduced in PR #483 (`feat(ai): HITL CI proposal workflow for AI agents`, commit `50dab9c`) is unreachable end-to-end on a real stack. Every call to `POST /api/cmdb/proposals` returns **500 Internal Server Error** with `AttributeError: 'NoneType' object has no attribute 'rollback'`, because the router and the MCP tool wrapper pass `db=None` to `services.cmdb_proposal_service.create_proposal`, which then forwards that `None` into `audit_service.record_critical_change → _persist_event`, where the code unconditionally calls `db.rollback()` on the except path.

This blocks the human-in-the-loop CI onboarding flow that was the main user-visible output of `feat-cmdb-ai-handoff`. The same root cause also breaks the MCP wrapper (`backend/mcp/cmdb_proposal_server.py:tool_propose_ci`).

## Environment

- Repo: `alexandervazquez98/next-gen`
- Branch / HEAD: `master` @ `9f5a3089cce3aeef4a2aaef389fad2ca7311fca8` (`v1.17.1`)
- Image: `next-gen-backend` (built locally from `backend/Dockerfile`)
- Postgres: `timescale/timescaledb:2.15.0-pg16` (`nexgen_postgres`), real schema.
- Neo4j: `neo4j:5.15.0` (`nexgen_neo4j`), with migration `005_ci_proposal_schema.cypher` applied.
- AI agent role seeded by `backend/seed_roles.py` (`AI_DIAGNOSTIC` with `AI_PROPOSE_CI`).
- `FEATURE_CMDB_PROPOSALS_ENABLED=true` (default is OFF; set explicitly via `docker-compose.yml` + `.env` — note: this env var is referenced in the compose file by our own patch, upstream `docker-compose.yml` does NOT pass it to the backend container, so the router is unreachable even with the flag set unless the operator wires the env var manually).

## Steps to reproduce

1. Deploy `master` (`v1.17.1`) with `FEATURE_CMDB_PROPOSALS_ENABLED=true` available in the backend container environment.
2. Confirm the router is mounted:

   ```bash
   curl -sS http://localhost:8000/api/cmdb/proposals/count?status=DRAFT
   # → 401 Not authenticated   (router is alive; flag is honored)
   ```

3. Seed an AI agent (the seeded `AI_DIAGNOSTIC` role does not auto-grant `AI_PROPOSE_CI` on the user row — see related issue below):

   ```sql
   UPDATE users SET permissions = ARRAY['AI_PROPOSE_CI']::text[]
   WHERE username = 'ai-test-bot';
   ```

4. Create a category the manifest references (the dev stack starts with zero categories):

   ```bash
   curl -X POST http://localhost:8000/api/categories \
     -H "Authorization: Bearer $ADMIN_TOKEN" \
     -H "Content-Type: application/json" \
     -d '{"name":"Router","description":"Network router category"}'
   ```

5. Submit a manifest as the AI agent:

   ```bash
   curl -X POST http://localhost:8000/api/cmdb/proposals \
     -H "Authorization: Bearer $AI_TOKEN" \
     -H "Content-Type: application/json" \
     -d '{
       "schema_version": 1,
       "ci": {
         "id": "CI-AIHANDOFF-001",
         "label": "AI Smoke Test Router",
         "category": "Router",
         "ip": "10.99.0.1",
         "status": "OK",
         "pollingInterval": 60
       },
       "rationale": "feat-cmdb-ai-handoff smoke test",
       "source_refs": ["chat:smoke"]
     }'
   ```

## Expected

Per `docs/ai/cmdb-proposals.md`:

```
HTTP 201
{ "proposal_id": "<uuid>", "status": "DRAFT", "version": 1, "created_at": "...", "resulted_ci_id": null }
```

## Actual

```
HTTP 500
{ "detail": "'NoneType' object has no attribute 'rollback'", "type": "AttributeError" }
```

## Server logs (excerpt)

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  ...
  File "/app/routers/cmdb_proposals.py", line 87, in create_proposal
    result = svc.create_proposal(...)
  File "/app/services/cmdb_proposal_service.py", line 298, in create_proposal
    _record(db=db, ...)
  File "/app/services/cmdb_proposal_service.py", line 172, in _record
    db.rollback()
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'rollback'
INFO: 172.18.0.1:46020 - "POST /api/cmdb/proposals HTTP/1.1" 500 Internal Server Error
```

The exception is also wrapped in an `ExceptionGroup` (AnyIO TaskGroup), so Starlette re-raises it twice in the logs.

## Root cause

`backend/routers/cmdb_proposals.py` (introduced by `50dab9c`):

```python
@router.post("")
async def create_proposal(
    request: Request,
    response: Response,
    manifest: dict[str, Any] = Body(...),
    current_user: User = Depends(get_current_active_user),  # noqa: B008
):
    ...
    result = svc.create_proposal(
        manifest=manifest,
        user=current_user,
        ai_agent_id=current_user.username,
        db=None,             # ← no DB session injected
        request=request,
    )
```

The same `db=None` pattern is used in `list_proposals`, `count_proposals`, `get_proposal`, `approve_proposal`, and `revoke_proposal` in the same file. It is also used in `backend/mcp/cmdb_proposal_server.py:tool_propose_ci` (lines ~194–206).

`backend/services/audit_service.py` (unchanged by PR #483, but assumed by it):

```python
def _persist_event(db: Session, event: AuditEvent) -> AuditEvent | None:
    try:
        db.add(event)
        db.commit()
        db.refresh(event)
        return event
    except Exception as exc:
        db.rollback()        # ← explodes when db is None
        logger.warning(...)
        return None
```

`backend/services/cmdb_proposal_service.py:_record` (introduced by `50dab9c`) forwards the `db` parameter into `audit_service.record_critical_change`, which in turn forwards it to `_persist_event`. The router passes `db=None`, so any failure inside `db.add/commit/refresh` (or any other path that catches and calls `db.rollback`) blows up.

## Why the existing tests did not catch this

`backend/tests/test_cmdb_proposal_router.py` patches the service entirely:

```python
with patch("services.cmdb_proposal_service.create_proposal", return_value=fake_row):
    response = client.post("/api/cmdb/proposals", json=_payload())
```

→ never enters the real `create_proposal`.

`backend/tests/test_cmdb_proposal_integration.py` stubs `audit_service.record_critical_change` at the module level (line ~84, `monkeypatch.setattr(audit_service, "record_critical_change", ...)`), so the `_record → record_critical_change → _persist_event` chain never runs with a real (or `None`) DB session.

Neither suite exercises the real `create_proposal → _record → record_critical_change` flow against a real Postgres session, so the `db=None` contract violation was never triggered in CI.

## Proposed fix (minimum, ~10 lines)

In `backend/routers/cmdb_proposals.py`:

1. Add imports:

   ```python
   from sqlalchemy.orm import Session
   from postgres_db import get_pg_db
   ```

2. For every endpoint handler (`create_proposal`, `list_proposals`, `count_proposals`, `get_proposal`, `approve_proposal`, `revoke_proposal`), add the dependency:

   ```python
   db: Session = Depends(get_pg_db),  # noqa: B008
   ```

3. Replace every `db=None` in the `svc.*` call with `db=db`.

Mirror the same three changes in `backend/mcp/cmdb_proposal_server.py:tool_propose_ci` (the MCP wrapper does not have a request scope, so it must lazily open its own session via `SessionLocal()` and close it in `finally` — see how `backend/scripts/cmdb_proposal_ttl_sweep.py` already does this at line ~150 with `_DefaultSessionLocal`).

A defensive alternative is to relax `record_critical_change` / `_persist_event` to accept `Optional[Session]` and short-circuit persistence when `db is None`, but that silently drops audit rows, which violates `REQ-AUDIT-001`. Not recommended.

## Recommended additional tests

1. **End-to-end router test** that does NOT stub `audit_service.record_critical_change` and uses the real Postgres session provided by the app's `get_pg_db` dependency. Goal: catch any future `db=None`-shaped regressions in the cmdb_proposals router and its MCP wrapper.
2. **Contract test** asserting that every `services.cmdb_proposal_service.*` public function accepts a non-`None` `db` and threads it through to `audit_service.record_critical_change`.
3. **`/api/categories` smoke** — current default stack ships with zero categories; the first proposal attempt always fails with `422 unknown_category`. Either seed default categories in `seed_roles.py` (next to the role seeding) or document this in `docs/ai/cmdb-proposals.md`.
4. **`AI_DIAGNOSTIC` user permissions** — `seed_roles.py` upgrades the *role* permissions but does not backfill `users.permissions` for existing AI agents. New AI agents are created with `permissions={}`. Either grant `AI_PROPOSE_CI` on user creation when `role in (AI_DIAGNOSTIC, AI_OPERATOR)` or document the manual `UPDATE users SET permissions = ARRAY['AI_PROPOSE_CI']` workaround.

## Impact / severity

- **Severity**: high. The headline user-facing flow of `feat-cmdb-ai-handoff` (PR #483, issue #467) is non-functional on any real deployment.
- **Affected endpoints**: all five `cmdb/proposals/*` endpoints (POST, GET list, GET count, GET detail, POST approve, POST revoke) and the MCP `propose_ci` tool.
- **Affected versions**: `v1.17.0` and `v1.17.1` (the merge commit and release prep). `v1.16.2` predates the feature and is unaffected.
- **Workaround**: none — there is no way to submit a CI proposal without the audit row, and the audit row is what guarantees `REQ-AUDIT-001`.

## Related

- PR: #483 (`feat(ai): HITL CI proposal workflow for AI agents`) — closes #467
- Issue: #467 (original proposal for the feature)
- Docs: `docs/ai/cmdb-proposals.md`
- Migration: `backend/migrations/005_ci_proposal_schema.cypher`
- Adjacent bugs observed during reproduction (separate issues recommended):
  - `docker-compose.yml` does not pass `FEATURE_CMDB_PROPOSALS_ENABLED` to the backend container (works locally only when the operator wires it in `.env` + compose `environment:`).
  - `seed_roles.py` upgrades role-level permissions but not `users.permissions` for AI personas.
  - `GET /api/categories` returns `[]` on a fresh stack; first proposal always `422 unknown_category`.

**Comment by alexandervazquez98** [comment]
Approved. Working on fix in PR (branch `fix/487-cmdb-proposals-db-session`). Plan:

1. Inject `db: Session = Depends(get_pg_db)` in all 6 handlers of `backend/routers/cmdb_proposals.py`.
2. Open/close own session in `backend/mcp/cmdb_proposal_server.py:tool_propose_ci` (following the `SessionLocal()` pattern used in `backend/scripts/cmdb_proposal_ttl_sweep.py`).
3. Add an end-to-end test `test_cmdb_proposal_router_e2e.py` that does NOT stub `audit_service.record_critical_change` to prevent future regressions of the same shape.
4. Validate `POST /api/cmdb/proposals` end-to-end on the dev server (`192.168.1.68`) **without merging to `main/master`** until the bug is confirmed fixed.

Refs: PR #483, issue #467 (closed-but-unverified).

**Comment by alexandervazquez98** [comment]
Fix verified end-to-end on `192.168.1.68` (`dev`, master `v1.17.1` + patch `94c97d14`).

Reproduced the exact failure first, then deployed PR #488 (`fix/487-cmdb-proposals-db-session`) to the dev server by checking out the branch (no merge to main/master) and rebuilding `next-gen-backend`.

After deploy, replayed the HITL flow against the real Postgres + Neo4j stack:

| Step | Endpoint | Result |
|---|---|---|
| AI agent propose | `POST /api/cmdb/proposals` | **HTTP 201** (`proposal_id=a21a446c-...`, `version=1`, `status=DRAFT`) |
| Operator list DRAFT | `GET /api/cmdb/proposals?status=DRAFT` | **HTTP 200** (proposal visible with full manifest) |
| Operator approve | `POST /api/cmdb/proposals/{id}/approve` | **HTTP 200** (`status=APPROVED`, `version=2`, `resulted_ci_id=CI-FIX487-001`) |
| Verify :CI in Neo4j | `MATCH (n:CI {id:"CI-FIX487-001"})` | Found row: `status=OK`, `brand=Cisco`, `model=ISR-1k`, `ip=10.99.1.1` |
| Verify audit rows | `SELECT FROM audit_events` | 2 SUCCESS rows: `CI_PROPOSAL_CREATE` (actor=ai-test-bot) and `CI_PROPOSAL_APPROVE` (actor=admin) |

Server state:
- Branch checked out on `/home/alex/next-gen`: `fix/487-cmdb-proposals-db-session @ 94c97d14`.
- `main` untouched at `9f5a3089 v1.17.1`.
- Backend container `nexgen_backend` running with the patched image.

PR: #488. Per operator instruction, NOT merging to main/master until the bug is corroborated fixed. Standing by for review/merge approval.
